# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

# you can delete this line if you're not using Docker
image: ubuntu:20.04

stages:
  - test
  - upload

clamav_scan:
  stage: test
  script:
    - bash test_clamav.sh
  artifacts:
    paths:
      - result_clamav.txt
    expire_in: 1h

virustotal_scan:
  stage: test
  script:
    - bash test_virustotal.sh
  artifacts:
    paths:
      - result_virustotal.txt
    expire_in: 1h

check_and_upload:
  stage: upload
  script:
    - ls -al
    - cat result_clamav.txt
    - cat result_virustotal.txt
    - >
      if grep -q "1" result_clamav.txt && grep -q "1" result_virustotal.txt; then
        apt-get update
        apt-get install git -y
        cd scan_file
        git init
        git config --global user.email "kenie7@gmail.com"
        git config --global user.name "okanchou9"
        git add --all
        git commit -m "GitLab Runner Push Scanned File to Clean Zone."
        git push https://okanchou9:WzoG-_2FTueAiTi-bhHc@gitlab.com/okanchou9/clean_zone.git HEAD:master
      else
        echo "SCAN failed and will not upload target file to clean zone. Please check detailed scan report and rescan again if need."
      fi
  dependencies:
    - clamav_scan
    - virustotal_scan

# include:
#   - template: Security/SAST.gitlab-ci.yml
