# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

# you can delete this line if you're not using Docker
image: ubuntu:20.04

before_script:
  # - apt-get update
  # - apt-get upgrade -y
  # - apt-get install clamav clamav-daemon -y
  # - clamscan --version
  # - service clamav-freshclam stop
  # - freshclam
  # - service clamav-freshclam start
  #- apt-get update -y
  #- apt-get install curl wget jq zip -y
  #- curl -s https://api.github.com/repos/VirusTotal/vt-cli/releases/latest | grep Linux64.zip | cut -d '"' -f 4 | wget -qi -
  #- curl -sL https://api.github.com/repos/VirusTotal/vt-cli/releases/latest | jq -r '.assets[].browser_download_url' | wget -qi -
  #- unzip Linux64.zip
  #- mv vt /usr/bin/
  #- vt init --apikey bbc2a5462848dbd9ded26e10ef5c62abb41c4fddea3153485d696f110a6875f8
  - echo "Do nothing"

after_script:
  - echo "Do nothing"

# clamav_scan:
#   stage: test
#   script:
#     - mkdir ~/123/
#     - tar jxvf gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2 --directory ~/123/
#     - clamscan -i -v -r ~/123/

virustotal_scan:
  stage: test
  script:
    #- vt scan file gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2 -v > virustotal_preresult.txt
    #- grep gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2 virustotal_preresult.txt | cut -d " " -f 2 | vt analysis - > virustotal_postresult.txt
    #- cat virustotal_postresult.txt
    - bash test.sh gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2

# include:
#   - template: Security/SAST.gitlab-ci.yml
